name: Build and Push Docker Image

# Chạy workflow khi có code push lên nhánh main
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      #####################################
      # a. Checkout code
      #####################################
      - name: Checkout repository
        uses: actions/checkout@v4

      #####################################
      # b. Login Docker Hub
      #####################################
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      #####################################
      # c. Setup Docker BuildX
      #####################################
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      #####################################
      # d. Setup Cache
      #####################################
      # Optional - giúp build nhanh hơn bằng cách sử dụng inline cache
      #####################################
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ngocchau170506/pollapp:latest
          cache-from: type=registry,ref=ngocchau170506/pollapp:latest
          cache-to: type=inline
